version: "3"
services:
    postgres:
        container_name: postgres_ec2
        build: .
        restart: always
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            PGDATA: /var/lib/postgresql/data
        volumes:
            - postgres-db-volume-ec2:/var/lib/postgresql/data
        ports:
            - "7777:5432"
volumes:
    postgres-db-volume-ec2:
